source "$AGENTBOARD_ROOT/lib/agentboard/core/base.sh"
source "$AGENTBOARD_ROOT/lib/agentboard/core/bootstrap_domains.sh"
source "$AGENTBOARD_ROOT/lib/agentboard/core/bootstrap_repos.sh"
source "$AGENTBOARD_ROOT/lib/agentboard/core/project_state.sh"
source "$AGENTBOARD_ROOT/lib/agentboard/core/project_detection.sh"
source "$AGENTBOARD_ROOT/lib/agentboard/core/facts_select.sh"
